services:
  slskd:
    image: slskd/slskd:${SLSKD_VERSION}
    container_name: slskd
    user: 1001:1001
    ports:
      - "5030:5030"
      - "5031:5031"
      - "50300:50300"
    env_file: .env
    volumes:
      - /opt/docker/standard/music/slskd:/app
      - "/media/music/Library:/music"
    restart: always
  
      
  navidrome:
    image: deluan/navidrome:${NAVIDROME_VERSION}
    user: 1001:1001 # should be owner of volumes
    ports:
      - "4533:4533"
    env_file: .env
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
       ND_LOGLEVEL: debug
    volumes:
      - "/opt/docker/standard/music/navidrome/data:/data"
      - "/media/music/Library:/music:ro"
      - "/media/music-old:/music-mp3:ro"

