services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:${SYNCTHING_VERSION}
    container_name: syncthing
    env_file: .env
    volumes:
      - /opt/docker/standard/syncthing/config:/config # Where syncthing stores its own settings
      - /opt/docker/standard/syncthing/files:/data/files
      - /media/books:/data/books       # THE SAME HOST PATH your Booklore uses
      - /home/ubuntu/Documents:/data/documents
    ports:
      - 8384:8384   # Web UI (Optional if using internal docker network for Tunnel)
      - 22000:22000/tcp # Sync traffic TCP
      - 22000:22000/udp # Sync traffic QUIC
      - 21027:21027/udp # Discovery
    restart: unless-stopped
