services:
  homepage:
    image: ghcr.io/gethomepage/homepage:${homepage_version}
    restart: unless-stopped
    container_name: homepage
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - /opt/docker/standard/homepage:/app/config # Make sure your local config directory exists
      - /opt/docker/standard/hompage/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
