volumes:
    mysql_data:

services:
    romm:
        image: rommapp/romm:latest
        container_name: romm
        restart: unless-stopped
        env_file: .env
        volumes:
            - /opt/docker/privileged/romm/resources:/romm/resources
            - /opt/docker/privileged/romm/redis-data:/redis-data
            - /media/games/library:/romm/library
            - /media/games/assets:/romm/assets
            - /media/games/config:/romm/config
        ports:
            - 7676:8080
        networks:
            - rommbridge
        depends_on:
            romm-db:
                condition: service_healthy
                restart: true

    romm-db:
        image: mariadb:latest
        container_name: romm-db
        restart: unless-stopped
        env_file: .env
        ports:
            - 3309:3306
        networks:
            - rommbridge
        volumes:
            - /opt/docker/privileged/romm/db:/var/lib/mysql
        healthcheck:
            test: [CMD, healthcheck.sh, --connect, --innodb_initialized]
            start_period: 30s
            start_interval: 10s
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    rommbridge:
        driver: bridge
