services:
  couchdb:
    image: couchdb:latest
    container_name: couchdb-for-ols
    user: 1001:1001
    env_file: .env
    volumes:
      - /opt/docker/standard/obsidian/data:/opt/couchdb/data
      - /opt/docker/standard/obsidian/etc:/opt/couchdb/etc/local.d
    ports:
      - 5984:5984
    restart: unless-stopped
