services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:${FRESHRSS_VERSION}
    container_name: freshrss
    env_file: .env
    volumes:
      - /opt/docker/standard/freshrss/config:/config
    ports:
      - 3080:80
    restart: unless-stopped
