# ==========================================
# FRONTEND APPS (Safe to update via Diun pings)
# ==========================================
audiobookshelf_version: "2.32.1"
booklore_version: "v2.0.5"
convertx_version: "v0.17.0"
freshrss_version: "1.28.0-ls291"
gitea_version: "1.25.2"
homepage_version: "v1.8.0"
navidrome_version: "0.60.3"
paperless_version: "2.20.3"
qbittorrent_version: "5.1.4-r2-ls442"
slskd_version: "0.24.5"
syncthing_version: "v2.0.12-ls205"
syncyomi_version: "v1.1.4"
tandoor_version: "2.3.6"
wallabag_version: "2.6.14"
diun_version: "4.31"
calibre_version: "9.5.0"
openclaw_version: "2026.3.22"
openclaw_browser_version: "0.3.0"

# ==========================================
# INFRASTRUCTURE (Louislam UI / Helper apps)
# ==========================================
dockge_version: "1.4.2"
uptime_kuma_version: "1.23.11"
flaresolverr_version: "v3.4.6"

# ==========================================
# DATABASES & BROKERS (DO NOT TOUCH UNLESS REQUIRED)
# ==========================================
booklore_mariadb_version: "11.4.5-r2-ls192"
paperless_broker_version: "8" # (Redis/RabbitMQ)
tandoor_db_version: "16-alpine" # (PostgreSQL)
obsidian_couchdb_version: "3.3"
