services:
  db_recipes:
    restart: always
    image: postgres:${TANDOOR_DB_VERSION}
    volumes:
      - /opt/docker/privileged/tandoor/postgresql:/var/lib/postgresql/data
    env_file:
      - .env

  web_recipes:
    restart: always
    image: vabene1111/recipes:${TANDOOR_VERSION}
    ports:
      - 7010:80
    env_file:
      - .env
    volumes:
      - /opt/docker/privileged/tandoor/staticfiles:/opt/recipes/staticfiles
      - /opt/docker/privileged/tandoor/mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes

volumes:
  staticfiles:
