services:
  calibre:
    image: lscr.io/linuxserver/calibre:${CALIBRE_VERSION}
    container_name: calibre
    env_file: .env
    security_opt:
      - seccomp:unconfined #optional
    volumes:
      # config location
      - /opt/docker/standard/books/calibre/config:/config
      # statging location, basically for metadata and stuff
      - /opt/docker/standard/books/calibre/library:/library
      # Final export location, ready for syncing!
      - /media/books:/media/books
    ports:
      - 8183:8080
    shm_size: "1gb"
    restart: unless-stopped

  kosync:
    container_name: kosync
    # TO MAKE ARM64 COMPATIBLE, DONT CHANGE!!!!!
    build: 
      context: https://github.com/jberlyn/kosync-dotnet.git#main
      dockerfile: Dockerfile
    restart: unless-stopped
    user: ${PUID}:${PGID}
    env_file: .env
    ports:
      - 8184:8080
    volumes:
      - /opt/docker/standard/books/kosync:/app/data
