services:
  booklore:
    image: booklore/booklore:${BOOKLORE_VERSION}
    # Alternative: Use GitHub Container Registry
    # image: ghcr.io/booklore-opt/docker/standard/booklore:latest
    container_name: booklore
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "${BOOKLORE_PORT}:${BOOKLORE_PORT}" 
    volumes:
      - /opt/docker/standard/booklore/data:/opt/docker/standard/data
      - /media/books/library:/books
      - /media/books/bookdrop:/bookdrop
    restart: unless-stopped

  mariadb:
    image: lscr.io/linuxserver/mariadb:${BOOKLORE_MARIADB_VERSION}
    container_name: mariadb
    env_file:
      - .env
    environment:
      - PUID=${DB_USER_ID}
      - PGID=${DB_GROUP_ID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - /opt/docker/standard/booklore/mariadb:/config
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10
