- name: Install rclone
  ansible.builtin.apt:
    name: rclone
    state: present

- name: Create rclone config directory if it does not exist
  ansible.builtin.file:
    path: /home/{{ server_user }}/.config/rclone
    state: directory
    mode: '0755'
    owner: "{{ server_user }}"
    group: "{{ server_user }}"

- name: Copy over rclone config
  ansible.builtin.template:
    src: rclone.conf.j2
    dest: /home/{{ server_user }}/.config/rclone/rclone.conf
    mode: 0600
    owner: "{{ server_user }}"
    group: "{{ server_user }}"


- name: Create /media mount point
  ansible.builtin.file:
    path: /media
    state: directory
    mode: '0755'
    owner: "{{ server_user }}"
    group: "{{ server_user }}"
  ignore_errors: true


- name: Enable user_allow_other in fuse.conf
  ansible.builtin.lineinfile:
    path: /etc/fuse.conf
    regexp: '^#?user_allow_other'
    line: 'user_allow_other'


- name: Create rclone log file with correct ownership
  ansible.builtin.file:
    path: /var/log/rclone.log
    state: file
    owner: "{{ server_user }}"
    group: "{{ server_user }}"
    mode: '0644'

- name: Copy over the rclone hetzner systemd service
  ansible.builtin.template:
    src: hetzner-storage.service.j2
    dest: /etc/systemd/system/hetzner-storage.service
  notify: restart rclone systemd service

- name: start rclone systemd service
  ansible.builtin.systemd_service:
    name: hetzner-storage.service
    enabled: true
    state: started
    daemon_reload: true
