- name: Politics
  head-widgets:
    - type: markets
      hide-header: true
      markets:
        - symbol: SPY
          name: S&P 500
        - symbol: NVDA
          name: NVIDIA
        - symbol: AAPL
          name: Apple
        - symbol: MSFT
          name: Microsoft
  columns:
    - size: small
      widgets: 
      - type: videos
        style: vertical-list
        collapse-after: 15
        channels:
          - UCdBXOyqr8cDshsp7kcKDAkg # Big A ?
          - UCUzmizB92LJ9oxf5T_snZNA # BadEmpanada
          - UCjY9R3_6sxfUViabj93Vnhw # BadEmpanada Live

    - size: full
      widgets:

      - type: iframe

        source: "https://s.tradingview.com/embed-widget/mini-symbol-overview/?symbol=XETR%3AVWCE&colorTheme=dark&dateRange=12M&isTransparent=true&autosize=true&trendLineColor=%232962FF&underLineColor=rgba(41%2C%2098%2C%20255%2C%200.3)"
        height: 350

      - type: bookmarks
        groups:
          - title: Finance
            color: 30 100 50
            links:
              - title: Scalable Capital
                url: https://scalable.capital/
              - title: C24 Bank
                url: https://www.c24.de/
              - title: JustETF
                url: https://www.justetf.com/
              - title: Finanzfluss
                url: https://www.finanzfluss.de/

    - size: small
      widgets:
      - type: clock
        hour-format: 24h
        timezones:
          - timezone: Europe/Berlin
            label: Karlsruhe
          - timezone: America/New_York
            label: New York
          - timezone: Asia/Tokyo
            label: Tokyo
      - type: weather
        units: metric
        hour-format: 24h
        location: Karlsruhe, Germany
      - type: calendar
        first-day-of-week: monday
